// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages_robocup_ssl_detection.proto

package ssl

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SSL_DetectionBall struct {
	Confidence           *float32 `protobuf:"fixed32,1,req,name=confidence" json:"confidence,omitempty"`
	Area                 *uint32  `protobuf:"varint,2,opt,name=area" json:"area,omitempty"`
	X                    *float32 `protobuf:"fixed32,3,req,name=x" json:"x,omitempty"`
	Y                    *float32 `protobuf:"fixed32,4,req,name=y" json:"y,omitempty"`
	Z                    *float32 `protobuf:"fixed32,5,opt,name=z" json:"z,omitempty"`
	PixelX               *float32 `protobuf:"fixed32,6,req,name=pixel_x,json=pixelX" json:"pixel_x,omitempty"`
	PixelY               *float32 `protobuf:"fixed32,7,req,name=pixel_y,json=pixelY" json:"pixel_y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SSL_DetectionBall) Reset()         { *m = SSL_DetectionBall{} }
func (m *SSL_DetectionBall) String() string { return proto.CompactTextString(m) }
func (*SSL_DetectionBall) ProtoMessage()    {}
func (*SSL_DetectionBall) Descriptor() ([]byte, []int) {
	return fileDescriptor_49252e7ed2122b91, []int{0}
}

func (m *SSL_DetectionBall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSL_DetectionBall.Unmarshal(m, b)
}
func (m *SSL_DetectionBall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSL_DetectionBall.Marshal(b, m, deterministic)
}
func (m *SSL_DetectionBall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSL_DetectionBall.Merge(m, src)
}
func (m *SSL_DetectionBall) XXX_Size() int {
	return xxx_messageInfo_SSL_DetectionBall.Size(m)
}
func (m *SSL_DetectionBall) XXX_DiscardUnknown() {
	xxx_messageInfo_SSL_DetectionBall.DiscardUnknown(m)
}

var xxx_messageInfo_SSL_DetectionBall proto.InternalMessageInfo

func (m *SSL_DetectionBall) GetConfidence() float32 {
	if m != nil && m.Confidence != nil {
		return *m.Confidence
	}
	return 0
}

func (m *SSL_DetectionBall) GetArea() uint32 {
	if m != nil && m.Area != nil {
		return *m.Area
	}
	return 0
}

func (m *SSL_DetectionBall) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *SSL_DetectionBall) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *SSL_DetectionBall) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

func (m *SSL_DetectionBall) GetPixelX() float32 {
	if m != nil && m.PixelX != nil {
		return *m.PixelX
	}
	return 0
}

func (m *SSL_DetectionBall) GetPixelY() float32 {
	if m != nil && m.PixelY != nil {
		return *m.PixelY
	}
	return 0
}

type SSL_DetectionRobot struct {
	Confidence           *float32 `protobuf:"fixed32,1,req,name=confidence" json:"confidence,omitempty"`
	RobotId              *uint32  `protobuf:"varint,2,opt,name=robot_id,json=robotId" json:"robot_id,omitempty"`
	X                    *float32 `protobuf:"fixed32,3,req,name=x" json:"x,omitempty"`
	Y                    *float32 `protobuf:"fixed32,4,req,name=y" json:"y,omitempty"`
	Orientation          *float32 `protobuf:"fixed32,5,opt,name=orientation" json:"orientation,omitempty"`
	PixelX               *float32 `protobuf:"fixed32,6,req,name=pixel_x,json=pixelX" json:"pixel_x,omitempty"`
	PixelY               *float32 `protobuf:"fixed32,7,req,name=pixel_y,json=pixelY" json:"pixel_y,omitempty"`
	Height               *float32 `protobuf:"fixed32,8,opt,name=height" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SSL_DetectionRobot) Reset()         { *m = SSL_DetectionRobot{} }
func (m *SSL_DetectionRobot) String() string { return proto.CompactTextString(m) }
func (*SSL_DetectionRobot) ProtoMessage()    {}
func (*SSL_DetectionRobot) Descriptor() ([]byte, []int) {
	return fileDescriptor_49252e7ed2122b91, []int{1}
}

func (m *SSL_DetectionRobot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSL_DetectionRobot.Unmarshal(m, b)
}
func (m *SSL_DetectionRobot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSL_DetectionRobot.Marshal(b, m, deterministic)
}
func (m *SSL_DetectionRobot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSL_DetectionRobot.Merge(m, src)
}
func (m *SSL_DetectionRobot) XXX_Size() int {
	return xxx_messageInfo_SSL_DetectionRobot.Size(m)
}
func (m *SSL_DetectionRobot) XXX_DiscardUnknown() {
	xxx_messageInfo_SSL_DetectionRobot.DiscardUnknown(m)
}

var xxx_messageInfo_SSL_DetectionRobot proto.InternalMessageInfo

func (m *SSL_DetectionRobot) GetConfidence() float32 {
	if m != nil && m.Confidence != nil {
		return *m.Confidence
	}
	return 0
}

func (m *SSL_DetectionRobot) GetRobotId() uint32 {
	if m != nil && m.RobotId != nil {
		return *m.RobotId
	}
	return 0
}

func (m *SSL_DetectionRobot) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *SSL_DetectionRobot) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *SSL_DetectionRobot) GetOrientation() float32 {
	if m != nil && m.Orientation != nil {
		return *m.Orientation
	}
	return 0
}

func (m *SSL_DetectionRobot) GetPixelX() float32 {
	if m != nil && m.PixelX != nil {
		return *m.PixelX
	}
	return 0
}

func (m *SSL_DetectionRobot) GetPixelY() float32 {
	if m != nil && m.PixelY != nil {
		return *m.PixelY
	}
	return 0
}

func (m *SSL_DetectionRobot) GetHeight() float32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

type SSL_DetectionFrame struct {
	FrameNumber          *uint32               `protobuf:"varint,1,req,name=frame_number,json=frameNumber" json:"frame_number,omitempty"`
	TCapture             *float64              `protobuf:"fixed64,2,req,name=t_capture,json=tCapture" json:"t_capture,omitempty"`
	TSent                *float64              `protobuf:"fixed64,3,req,name=t_sent,json=tSent" json:"t_sent,omitempty"`
	CameraId             *uint32               `protobuf:"varint,4,req,name=camera_id,json=cameraId" json:"camera_id,omitempty"`
	Balls                []*SSL_DetectionBall  `protobuf:"bytes,5,rep,name=balls" json:"balls,omitempty"`
	RobotsYellow         []*SSL_DetectionRobot `protobuf:"bytes,6,rep,name=robots_yellow,json=robotsYellow" json:"robots_yellow,omitempty"`
	RobotsBlue           []*SSL_DetectionRobot `protobuf:"bytes,7,rep,name=robots_blue,json=robotsBlue" json:"robots_blue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SSL_DetectionFrame) Reset()         { *m = SSL_DetectionFrame{} }
func (m *SSL_DetectionFrame) String() string { return proto.CompactTextString(m) }
func (*SSL_DetectionFrame) ProtoMessage()    {}
func (*SSL_DetectionFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_49252e7ed2122b91, []int{2}
}

func (m *SSL_DetectionFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSL_DetectionFrame.Unmarshal(m, b)
}
func (m *SSL_DetectionFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSL_DetectionFrame.Marshal(b, m, deterministic)
}
func (m *SSL_DetectionFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSL_DetectionFrame.Merge(m, src)
}
func (m *SSL_DetectionFrame) XXX_Size() int {
	return xxx_messageInfo_SSL_DetectionFrame.Size(m)
}
func (m *SSL_DetectionFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_SSL_DetectionFrame.DiscardUnknown(m)
}

var xxx_messageInfo_SSL_DetectionFrame proto.InternalMessageInfo

func (m *SSL_DetectionFrame) GetFrameNumber() uint32 {
	if m != nil && m.FrameNumber != nil {
		return *m.FrameNumber
	}
	return 0
}

func (m *SSL_DetectionFrame) GetTCapture() float64 {
	if m != nil && m.TCapture != nil {
		return *m.TCapture
	}
	return 0
}

func (m *SSL_DetectionFrame) GetTSent() float64 {
	if m != nil && m.TSent != nil {
		return *m.TSent
	}
	return 0
}

func (m *SSL_DetectionFrame) GetCameraId() uint32 {
	if m != nil && m.CameraId != nil {
		return *m.CameraId
	}
	return 0
}

func (m *SSL_DetectionFrame) GetBalls() []*SSL_DetectionBall {
	if m != nil {
		return m.Balls
	}
	return nil
}

func (m *SSL_DetectionFrame) GetRobotsYellow() []*SSL_DetectionRobot {
	if m != nil {
		return m.RobotsYellow
	}
	return nil
}

func (m *SSL_DetectionFrame) GetRobotsBlue() []*SSL_DetectionRobot {
	if m != nil {
		return m.RobotsBlue
	}
	return nil
}

func init() {
	proto.RegisterType((*SSL_DetectionBall)(nil), "SSL_DetectionBall")
	proto.RegisterType((*SSL_DetectionRobot)(nil), "SSL_DetectionRobot")
	proto.RegisterType((*SSL_DetectionFrame)(nil), "SSL_DetectionFrame")
}

func init() {
	proto.RegisterFile("messages_robocup_ssl_detection.proto", fileDescriptor_49252e7ed2122b91)
}

var fileDescriptor_49252e7ed2122b91 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x8b, 0xd4, 0x30,
	0x1c, 0xc5, 0x49, 0x67, 0xda, 0xa9, 0xff, 0xce, 0x1c, 0x8c, 0xa8, 0x11, 0x41, 0xea, 0xe0, 0xa1,
	0xa7, 0x39, 0x88, 0x07, 0xcf, 0xa3, 0x08, 0x0b, 0xe2, 0x21, 0x73, 0x71, 0xbd, 0x84, 0xb4, 0xfd,
	0xef, 0x6e, 0x21, 0x6d, 0x4a, 0x92, 0x62, 0xbb, 0x1f, 0x47, 0x3f, 0x94, 0x5f, 0x47, 0x92, 0x56,
	0x1c, 0x5d, 0x54, 0xbc, 0xe5, 0xf7, 0xf2, 0xfe, 0xe9, 0x7b, 0x69, 0xe0, 0x45, 0x8b, 0xd6, 0xca,
	0x6b, 0xb4, 0xc2, 0xe8, 0x52, 0x57, 0x43, 0x2f, 0xac, 0x55, 0xa2, 0x46, 0x87, 0x95, 0x6b, 0x74,
	0x77, 0xe8, 0x8d, 0x76, 0x7a, 0xff, 0x95, 0xc0, 0xfd, 0xd3, 0xe9, 0xbd, 0x78, 0xfb, 0x43, 0x3f,
	0x4a, 0xa5, 0xe8, 0x33, 0x80, 0x4a, 0x77, 0x57, 0x4d, 0x8d, 0x5d, 0x85, 0x8c, 0xe4, 0x51, 0x11,
	0xf1, 0x33, 0x85, 0x52, 0x58, 0x4b, 0x83, 0x92, 0x45, 0x39, 0x29, 0x76, 0x3c, 0xac, 0xe9, 0x16,
	0xc8, 0xc8, 0x56, 0xc1, 0x4a, 0x46, 0x4f, 0x13, 0x5b, 0xcf, 0x34, 0x79, 0xba, 0x65, 0x71, 0x4e,
	0x3c, 0xdd, 0xd2, 0xc7, 0xb0, 0xe9, 0x9b, 0x11, 0x95, 0x18, 0x59, 0x12, 0x1c, 0x49, 0xc0, 0x8f,
	0x3f, 0x37, 0x26, 0xb6, 0x39, 0xdb, 0xb8, 0xdc, 0x7f, 0x23, 0x40, 0x7f, 0x49, 0xc9, 0x75, 0xa9,
	0xdd, 0x3f, 0x63, 0x3e, 0x81, 0xd4, 0x77, 0x77, 0xa2, 0xa9, 0x97, 0xa8, 0x9b, 0xc0, 0x17, 0xf5,
	0x5f, 0xd3, 0xe6, 0x90, 0x69, 0xd3, 0x60, 0xe7, 0xa4, 0xff, 0xd4, 0x92, 0xfb, 0x5c, 0xfa, 0xff,
	0x06, 0xf4, 0x11, 0x24, 0x37, 0xd8, 0x5c, 0xdf, 0x38, 0x96, 0x86, 0xe3, 0x16, 0xda, 0x7f, 0x89,
	0x7e, 0x6b, 0xf6, 0xce, 0xc8, 0x16, 0xe9, 0x73, 0xd8, 0x5e, 0xf9, 0x85, 0xe8, 0x86, 0xb6, 0x44,
	0x13, 0xba, 0xed, 0x78, 0x16, 0xb4, 0x0f, 0x41, 0xa2, 0x4f, 0xe1, 0x9e, 0x13, 0x95, 0xec, 0xdd,
	0x60, 0x90, 0x45, 0x79, 0x54, 0x10, 0x9e, 0xba, 0x37, 0x33, 0xd3, 0x87, 0x90, 0x38, 0x61, 0xb1,
	0x73, 0xa1, 0x23, 0xe1, 0xb1, 0x3b, 0x61, 0xe7, 0xfc, 0x4c, 0x25, 0x5b, 0x34, 0xd2, 0xdf, 0xc8,
	0x3a, 0x9c, 0x99, 0xce, 0xc2, 0x45, 0x4d, 0x0b, 0x88, 0x4b, 0xa9, 0x94, 0x65, 0x71, 0xbe, 0x2a,
	0xb2, 0x97, 0xf4, 0x70, 0xe7, 0x5d, 0xf0, 0xd9, 0x40, 0x5f, 0xc3, 0x2e, 0xdc, 0xa3, 0x15, 0x13,
	0x2a, 0xa5, 0x3f, 0xb3, 0x24, 0x4c, 0x3c, 0x38, 0xdc, 0xfd, 0x47, 0x7c, 0x3b, 0x3b, 0x2f, 0x83,
	0x91, 0xbe, 0x82, 0x6c, 0x99, 0x2c, 0xd5, 0x80, 0x6c, 0xf3, 0xe7, 0x39, 0x98, 0x7d, 0x47, 0x35,
	0xe0, 0x31, 0xfe, 0xb4, 0xb2, 0x56, 0x7d, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x1e, 0xcf, 0x67,
	0xd2, 0x02, 0x00, 0x00,
}
