// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages_robocup_ssl_wrapper.proto

package ssl

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Timestamp struct {
	UnixTimestamp        int32    `protobuf:"varint,1,opt,name=unix_timestamp,json=unixTimestamp,proto3" json:"unix_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf05487903c52d35, []int{0}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetUnixTimestamp() int32 {
	if m != nil {
		return m.UnixTimestamp
	}
	return 0
}

type SSL_WrapperPacket struct {
	Detection            *SSL_DetectionFrame `protobuf:"bytes,1,opt,name=detection,proto3" json:"detection,omitempty"`
	Geometry             *SSL_GeometryData   `protobuf:"bytes,2,opt,name=geometry,proto3" json:"geometry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SSL_WrapperPacket) Reset()         { *m = SSL_WrapperPacket{} }
func (m *SSL_WrapperPacket) String() string { return proto.CompactTextString(m) }
func (*SSL_WrapperPacket) ProtoMessage()    {}
func (*SSL_WrapperPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf05487903c52d35, []int{1}
}

func (m *SSL_WrapperPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SSL_WrapperPacket.Unmarshal(m, b)
}
func (m *SSL_WrapperPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SSL_WrapperPacket.Marshal(b, m, deterministic)
}
func (m *SSL_WrapperPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SSL_WrapperPacket.Merge(m, src)
}
func (m *SSL_WrapperPacket) XXX_Size() int {
	return xxx_messageInfo_SSL_WrapperPacket.Size(m)
}
func (m *SSL_WrapperPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_SSL_WrapperPacket.DiscardUnknown(m)
}

var xxx_messageInfo_SSL_WrapperPacket proto.InternalMessageInfo

func (m *SSL_WrapperPacket) GetDetection() *SSL_DetectionFrame {
	if m != nil {
		return m.Detection
	}
	return nil
}

func (m *SSL_WrapperPacket) GetGeometry() *SSL_GeometryData {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func init() {
	proto.RegisterType((*Timestamp)(nil), "Timestamp")
	proto.RegisterType((*SSL_WrapperPacket)(nil), "SSL_WrapperPacket")
}

func init() { proto.RegisterFile("messages_robocup_ssl_wrapper.proto", fileDescriptor_bf05487903c52d35) }

var fileDescriptor_bf05487903c52d35 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0x47, 0x8d, 0x52, 0x69, 0xc7, 0x3f, 0xd0, 0xf5, 0x52, 0x7a, 0x92, 0xa8, 0xe0, 0xc5, 0x45,
	0xe3, 0x5d, 0x50, 0xaa, 0x45, 0x50, 0x90, 0x54, 0x10, 0xbc, 0x2c, 0x9b, 0x38, 0x94, 0x60, 0xb6,
	0xb3, 0xec, 0x4c, 0x50, 0xbf, 0xbd, 0x74, 0xdb, 0xc4, 0x83, 0xbd, 0x3e, 0xde, 0x6f, 0x78, 0x03,
	0xa9, 0x43, 0x66, 0x3b, 0x47, 0x36, 0x81, 0x0a, 0x2a, 0x1b, 0x6f, 0x98, 0x6b, 0xf3, 0x15, 0xac,
	0xf7, 0x18, 0xb4, 0x0f, 0x24, 0x34, 0x3e, 0xdd, 0xe8, 0x7c, 0xa0, 0x60, 0x29, 0x15, 0x2d, 0xd6,
	0xd6, 0xc9, 0x46, 0x6b, 0x8e, 0xe4, 0x50, 0xc2, 0xcf, 0x4a, 0x4a, 0x33, 0x18, 0xbc, 0x56, 0x0e,
	0x59, 0xac, 0xf3, 0xea, 0x0c, 0x0e, 0x9b, 0x45, 0xf5, 0x6d, 0xa4, 0x25, 0xa3, 0xe4, 0x38, 0x39,
	0xef, 0xe5, 0x07, 0x4b, 0xda, 0x69, 0x69, 0x03, 0xc3, 0xd9, 0xec, 0xc9, 0xbc, 0xad, 0x9a, 0x5e,
	0x6c, 0xf9, 0x89, 0xa2, 0xae, 0x60, 0xd0, 0x05, 0xc4, 0xd9, 0x5e, 0x76, 0xa4, 0x97, 0xda, 0xa4,
	0xa5, 0x0f, 0xc1, 0x3a, 0xcc, 0xff, 0x2c, 0x75, 0x01, 0xfd, 0xb6, 0x66, 0xb4, 0x1d, 0x17, 0xc3,
	0xb8, 0x98, 0xae, 0xe1, 0xc4, 0x8a, 0xcd, 0x3b, 0x25, 0xbb, 0x81, 0xfd, 0x9c, 0x0a, 0x7a, 0x7c,
	0xbe, 0xbf, 0x95, 0xda, 0xb2, 0xd2, 0xd0, 0x9f, 0xa2, 0xc4, 0xab, 0x0a, 0x74, 0x97, 0x37, 0x56,
	0xfa, 0x5f, 0x5d, 0xba, 0x75, 0x99, 0xdc, 0xf5, 0xde, 0x77, 0x98, 0xeb, 0x62, 0x37, 0x3e, 0x7e,
	0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x54, 0x54, 0xfc, 0x2d, 0x69, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RoboIMEAtlasClient is the client API for RoboIMEAtlas service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RoboIMEAtlasClient interface {
	GetFrame(ctx context.Context, in *Timestamp, opts ...grpc.CallOption) (RoboIMEAtlas_GetFrameClient, error)
}

type roboIMEAtlasClient struct {
	cc *grpc.ClientConn
}

func NewRoboIMEAtlasClient(cc *grpc.ClientConn) RoboIMEAtlasClient {
	return &roboIMEAtlasClient{cc}
}

func (c *roboIMEAtlasClient) GetFrame(ctx context.Context, in *Timestamp, opts ...grpc.CallOption) (RoboIMEAtlas_GetFrameClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RoboIMEAtlas_serviceDesc.Streams[0], "/RoboIMEAtlas/GetFrame", opts...)
	if err != nil {
		return nil, err
	}
	x := &roboIMEAtlasGetFrameClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RoboIMEAtlas_GetFrameClient interface {
	Recv() (*SSL_WrapperPacket, error)
	grpc.ClientStream
}

type roboIMEAtlasGetFrameClient struct {
	grpc.ClientStream
}

func (x *roboIMEAtlasGetFrameClient) Recv() (*SSL_WrapperPacket, error) {
	m := new(SSL_WrapperPacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RoboIMEAtlasServer is the server API for RoboIMEAtlas service.
type RoboIMEAtlasServer interface {
	GetFrame(*Timestamp, RoboIMEAtlas_GetFrameServer) error
}

// UnimplementedRoboIMEAtlasServer can be embedded to have forward compatible implementations.
type UnimplementedRoboIMEAtlasServer struct {
}

func (*UnimplementedRoboIMEAtlasServer) GetFrame(req *Timestamp, srv RoboIMEAtlas_GetFrameServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFrame not implemented")
}

func RegisterRoboIMEAtlasServer(s *grpc.Server, srv RoboIMEAtlasServer) {
	s.RegisterService(&_RoboIMEAtlas_serviceDesc, srv)
}

func _RoboIMEAtlas_GetFrame_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Timestamp)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RoboIMEAtlasServer).GetFrame(m, &roboIMEAtlasGetFrameServer{stream})
}

type RoboIMEAtlas_GetFrameServer interface {
	Send(*SSL_WrapperPacket) error
	grpc.ServerStream
}

type roboIMEAtlasGetFrameServer struct {
	grpc.ServerStream
}

func (x *roboIMEAtlasGetFrameServer) Send(m *SSL_WrapperPacket) error {
	return x.ServerStream.SendMsg(m)
}

var _RoboIMEAtlas_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RoboIMEAtlas",
	HandlerType: (*RoboIMEAtlasServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFrame",
			Handler:       _RoboIMEAtlas_GetFrame_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "messages_robocup_ssl_wrapper.proto",
}
